"""
test_demo_payment.py
====================
Comprehensive Unit and Integration Tests for Demo Payment Mode in CampusPrint.

Covers:
1. Demo payment succeeds when DEMO_PAYMENT_MODE=true.
2. Demo payment fails when DEMO_PAYMENT_MODE=false.
3. Demo payment cannot change the order amount.
4. Demo payment requires a valid order.
5. Demo payment changes payment status to Paid.
6. Demo payment changes order status to Order Received.
7. Demo transaction ID is generated by backend.
8. Multiple demo payment methods (Card, UPI, QR, Net Banking).
9. /api/payment/config reflects DEMO_PAYMENT_MODE state.
"""

import os
import unittest
from unittest.mock import patch

from app import create_app
from config import Config
from database import create_order, get_order_by_id


class TestDemoPaymentMode(unittest.TestCase):
    def setUp(self):
        self.app = create_app()
        self.client = self.app.test_client()

    def _create_test_order(self, total_price=50.0, status="Pending Payment", payment_status="Pending"):
        return create_order({
            "student_name": "Demo Student",
            "roll_number": "22X01A0501",
            "phone_number": "9876543210",
            "email": "demo.student@mlrit.ac.in",
            "document_name": "demo_assignment.pdf",
            "stored_filename": "demo_assignment.pdf",
            "pages": 10,
            "copies": 1,
            "total_price": total_price,
            "order_status": status,
            "payment_status": payment_status,
            "payment_method": "Pending",
        })

    # ── Test 1: Demo payment succeeds when DEMO_PAYMENT_MODE=true ─────────────
    def test_01_demo_payment_succeeds_when_enabled(self):
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            order = self._create_test_order(total_price=35.0)
            res = self.client.post("/api/payment/demo", json={
                "order_id": order["order_id"],
                "payment_method": "Demo Card",
                "cardholder_name": "Demo Student"
            })
            self.assertEqual(res.status_code, 200)
            data = res.get_json()
            self.assertTrue(data["success"])
            self.assertEqual(data["payment_status"], "Paid")
            self.assertEqual(data["order_status"], "Order Received")
            self.assertIn("CPDEMO-", data["demo_transaction_id"])
            self.assertEqual(data["payment_method"], "Demo Card")

    # ── Test 2: Demo payment fails when DEMO_PAYMENT_MODE=false ───────────────
    def test_02_demo_payment_fails_when_disabled(self):
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "false"}):
            order = self._create_test_order(total_price=20.0)
            res = self.client.post("/api/payment/demo", json={
                "order_id": order["order_id"],
                "payment_method": "Demo UPI"
            })
            self.assertEqual(res.status_code, 403)
            data = res.get_json()
            self.assertFalse(data["success"])
            self.assertIn("disabled", data["error"].lower())

            # Verify order was NOT marked paid
            stored = get_order_by_id(order["order_id"])
            self.assertNotEqual(stored["payment_status"].lower(), "paid")

    # ── Test 3: Demo payment cannot change the order amount ───────────────────
    def test_03_demo_payment_cannot_change_order_amount(self):
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            legitimate_price = 75.0
            order = self._create_test_order(total_price=legitimate_price)

            # Malicious attempt to pass altered amount in request payload
            res = self.client.post("/api/payment/demo", json={
                "order_id": order["order_id"],
                "payment_method": "Demo UPI",
                "amount": 1.0,
                "order_amount": 1.0,
                "total_price": 1.0
            })
            self.assertEqual(res.status_code, 200)
            data = res.get_json()
            self.assertTrue(data["success"])

            # Authoritative amount in database must remain 75.0
            stored = get_order_by_id(order["order_id"])
            self.assertEqual(float(stored["total_price"]), legitimate_price)
            self.assertEqual(float(data["order"]["total_price"]), legitimate_price)

    # ── Test 4: Demo payment requires a valid order ───────────────────────────
    def test_04_demo_payment_requires_valid_order(self):
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            # 4a. Missing order_id
            res1 = self.client.post("/api/payment/demo", json={
                "payment_method": "Demo QR"
            })
            self.assertEqual(res1.status_code, 400)
            self.assertFalse(res1.get_json()["success"])

            # 4b. Nonexistent order_id
            res2 = self.client.post("/api/payment/demo", json={
                "order_id": "ORD-DOESNOTEXIST-999",
                "payment_method": "Demo QR"
            })
            self.assertEqual(res2.status_code, 404)
            self.assertFalse(res2.get_json()["success"])

            # 4c. Already paid order
            paid_order = self._create_test_order(total_price=30.0, payment_status="Paid")
            res3 = self.client.post("/api/payment/demo", json={
                "order_id": paid_order["order_id"],
                "payment_method": "Demo Card"
            })
            self.assertEqual(res3.status_code, 400)
            self.assertIn("already paid", res3.get_json()["error"].lower())

    # ── Test 5: Demo payment changes payment status to Paid ───────────────────
    def test_05_demo_payment_changes_payment_status_to_paid(self):
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            order = self._create_test_order(total_price=40.0, payment_status="Pending")
            res = self.client.post("/api/payment/demo", json={
                "order_id": order["order_id"],
                "payment_method": "Demo Net Banking"
            })
            self.assertEqual(res.status_code, 200)

            stored = get_order_by_id(order["order_id"])
            self.assertEqual(stored["payment_status"], "Paid")
            self.assertIsNotNone(stored.get("payment_completed_at"))

    # ── Test 6: Demo payment changes order status to Order Received ───────────
    def test_06_demo_payment_changes_order_status_to_order_received(self):
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            order = self._create_test_order(total_price=25.0, status="Pending Payment")
            res = self.client.post("/api/payment/demo", json={
                "order_id": order["order_id"],
                "payment_method": "Demo QR"
            })
            self.assertEqual(res.status_code, 200)

            stored = get_order_by_id(order["order_id"])
            self.assertEqual(stored["order_status"], "Order Received")

    # ── Test 7: Demo transaction ID is generated by backend ───────────────────
    def test_07_demo_transaction_id_is_generated_by_backend(self):
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            order = self._create_test_order(total_price=60.0)
            res = self.client.post("/api/payment/demo", json={
                "order_id": order["order_id"],
                "payment_method": "Demo UPI",
                "upi_id": "demo@upi"
            })
            self.assertEqual(res.status_code, 200)
            data = res.get_json()

            txn_id = data.get("demo_transaction_id")
            self.assertIsNotNone(txn_id)
            self.assertTrue(txn_id.startswith(f"CPDEMO-{order['order_id']}"))

            stored = get_order_by_id(order["order_id"])
            self.assertEqual(stored["payment_id"], txn_id)

    # ── Test 8: All four demo payment methods map appropriately ──────────────
    def test_08_all_demo_methods_supported(self):
        methods = [
            ("card", "Demo Card"),
            ("upi", "Demo UPI"),
            ("qr", "Demo QR"),
            ("netbanking", "Demo Net Banking"),
        ]
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            for input_method, expected_label in methods:
                order = self._create_test_order(total_price=15.0)
                res = self.client.post("/api/payment/demo", json={
                    "order_id": order["order_id"],
                    "payment_method": input_method
                })
                self.assertEqual(res.status_code, 200)
                data = res.get_json()
                self.assertEqual(data["payment_method"], expected_label)
                stored = get_order_by_id(order["order_id"])
                self.assertEqual(stored["payment_method"], expected_label)

    # ── Test 9: /api/payment/config reflects DEMO_PAYMENT_MODE state ──────────
    def test_09_payment_config_endpoint_reflects_demo_mode(self):
        # When DEMO_PAYMENT_MODE=true
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "true"}):
            res_true = self.client.get("/api/payment/config")
            self.assertEqual(res_true.status_code, 200)
            self.assertTrue(res_true.get_json()["demo_payment_mode"])

        # When DEMO_PAYMENT_MODE=false
        with patch.dict(os.environ, {"DEMO_PAYMENT_MODE": "false"}):
            res_false = self.client.get("/api/payment/config")
            self.assertEqual(res_false.status_code, 200)
            self.assertFalse(res_false.get_json()["demo_payment_mode"])


if __name__ == "__main__":
    unittest.main()
